// <auto-generated />
using System;
using Babian.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Babian.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402132749_AddLongTextForImages")]
    partial class AddLongTextForImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Babian.Domain.Entities.Drink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("base_price");

                    b.Property<string>("Category")
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("current_price");

                    b.Property<Guid?>("GlobalDrinkId")
                        .HasColumnType("char(36)")
                        .HasColumnName("global_drink_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("MarketPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("market_price");

                    b.Property<Guid?>("MarketSessionId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("max_price");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("min_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("owner_id");

                    b.Property<string>("Plu")
                        .HasColumnType("longtext")
                        .HasColumnName("plu");

                    b.Property<string>("Volume")
                        .HasColumnType("longtext")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("GlobalDrinkId");

                    b.HasIndex("MarketSessionId");

                    b.HasIndex("OwnerId");

                    b.ToTable("drinks", (string)null);
                });

            modelBuilder.Entity("Babian.Domain.Entities.GlobalDrink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DefaultBasePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("default_base_price");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Plu")
                        .HasColumnType("longtext")
                        .HasColumnName("plu");

                    b.Property<string>("Volume")
                        .HasColumnType("longtext")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.ToTable("global_drinks", (string)null);
                });

            modelBuilder.Entity("Babian.Domain.Entities.MarketConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BarmanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("barman_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CycleDurationSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60)
                        .HasColumnName("cycle_duration_seconds");

                    b.Property<decimal>("DecreaseOthers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0.05m)
                        .HasColumnName("decrease_others");

                    b.Property<decimal>("IncreasePerOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0.10m)
                        .HasColumnName("increase_per_order");

                    b.Property<string>("RankingGroups")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("ranking_groups");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BarmanId")
                        .IsUnique();

                    b.ToTable("market_configs", (string)null);
                });

            modelBuilder.Entity("Babian.Domain.Entities.MarketEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BarmanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DrinkIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("market_events", (string)null);
                });

            modelBuilder.Entity("Babian.Domain.Entities.MarketSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentCycleNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("current_cycle_number");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastPriceUpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_price_update_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("market_sessions", (string)null);
                });

            modelBuilder.Entity("Babian.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("int")
                        .HasColumnName("cycle_number");

                    b.Property<Guid>("DrinkId")
                        .HasColumnType("char(36)")
                        .HasColumnName("drink_id");

                    b.Property<Guid?>("MarketSessionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("market_session_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("PriceAtOrder")
                        .HasColumnType("numeric")
                        .HasColumnName("price_at_order");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DrinkId");

                    b.HasIndex("MarketSessionId");

                    b.HasIndex("OwnerId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Babian.Domain.Entities.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("int")
                        .HasColumnName("cycle_number");

                    b.Property<Guid>("DrinkId")
                        .HasColumnType("char(36)")
                        .HasColumnName("drink_id");

                    b.Property<Guid?>("MarketSessionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("market_session_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<decimal>("Variation")
                        .HasColumnType("numeric")
                        .HasColumnName("variation");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DrinkId");

                    b.HasIndex("MarketSessionId");

                    b.ToTable("price_histories", (string)null);
                });

            modelBuilder.Entity("Babian.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RestaurantId")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Babian.Domain.Entities.Drink", b =>
                {
                    b.HasOne("Babian.Domain.Entities.GlobalDrink", "GlobalDrink")
                        .WithMany()
                        .HasForeignKey("GlobalDrinkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Babian.Domain.Entities.MarketSession", "MarketSession")
                        .WithMany()
                        .HasForeignKey("MarketSessionId");

                    b.HasOne("Babian.Domain.Entities.User", "Owner")
                        .WithMany("Drinks")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalDrink");

                    b.Navigation("MarketSession");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Babian.Domain.Entities.MarketConfig", b =>
                {
                    b.HasOne("Babian.Domain.Entities.User", "Barman")
                        .WithMany()
                        .HasForeignKey("BarmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barman");
                });

            modelBuilder.Entity("Babian.Domain.Entities.MarketSession", b =>
                {
                    b.HasOne("Babian.Domain.Entities.User", "Owner")
                        .WithMany("MarketSessions")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Babian.Domain.Entities.Order", b =>
                {
                    b.HasOne("Babian.Domain.Entities.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Babian.Domain.Entities.MarketSession", "MarketSession")
                        .WithMany()
                        .HasForeignKey("MarketSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Babian.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("MarketSession");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Babian.Domain.Entities.PriceHistory", b =>
                {
                    b.HasOne("Babian.Domain.Entities.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Babian.Domain.Entities.MarketSession", "MarketSession")
                        .WithMany()
                        .HasForeignKey("MarketSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Drink");

                    b.Navigation("MarketSession");
                });

            modelBuilder.Entity("Babian.Domain.Entities.User", b =>
                {
                    b.Navigation("Drinks");

                    b.Navigation("MarketSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
